### ISSUE TITLE
Fan curve after the Ubuntu patch.

### ISSUE THREAD

**Issue by sblantipodi** [NikPiermafrost/rpi5-ubuntu-server-fan-script#3]
Hi there,
I would like to use your script with Ubuntu 23.10 but now that Ubuntu fixed the fan issue this script does not work correctly.

How can I disable the Ubuntu fan control and use your script?
I would like to customize the fan curve, this is why I want to use your script.

Thanks 
Ciao

**Comment by NikPiermafrost** [comment]
> Hi there, I would like to use your script with Ubuntu 23.10 but now that Ubuntu fixed the fan issue this script does not work correctly.
> 
> How can I disable the Ubuntu fan control and use your script? I would like to customize the fan curve, this is why I want to use your script.
> 
> Thanks Ciao

[Quoting this article in the Raspberry Pi forums](https://forums.raspberrypi.com/viewtopic.php?t=359778)

Running pinctrl FAN_PWM op dl at boot actually removes control of the fan from the kernel, and a quick test worked pretty well. I am currently running on raspberry pi os but i think there are the same packages in ubuntu too

**Comment by sblantipodi** [comment]
ok thank you very much :)
